version: '2'

services:
  mapd-core:
    image: 'mapd/mapd-ce-cuda'
    ports:
      - 9090:9090
      - 9091:9091
      - 9092:9092
    volumes:
      - ./mapd-ml-storage:/mapd-storage
    ipc: host
  mapd-ml:
    image: 'mapd/ml'
    ports:
      - 8888:8888
    links:
      - mapd-core
    ipc: host

